image:
  repository: kong/kong-gateway
  tag: "3.10.0.0"

secretVolumes:
- kong-cluster-cert
- kong-proxy-cert

manager:
  enabled: false

admin:
  enabled: false

extraLabels:
  tags.datadoghq.com/env: "demo"
  tags.datadoghq.com/service: "kong-dp"
  tags.datadoghq.com/version: "3.8.1.0"

# plugins:
#   configMaps:
#     - name: kong-plugin-log-extend
#       pluginName: log-extend

# Annotation to be added to Kong pods
podAnnotations:
  kuma.io/gateway: enabled
  traffic.sidecar.istio.io/includeInboundPorts: ""
  # Datadog related annotations (Observability stack: DataDog)
  ad.datadoghq.com/proxy.check_names: '["kong"]'
  ad.datadoghq.com/proxy.init_configs: '[{}]'
  ad.datadoghq.com/proxy.instances: '[{"openmetrics_endpoint": "http://%%host%%:8100/metrics"}]'
  ad.datadoghq.com/proxy.logs: '[{"source": "kong", "service": "kong-dp"}]'
  # Dynatrace related annotations (Observability stack: Dynatrace)
  metrics.dynatrace.com/scrape: 'true'
  metrics.dynatrace.com/path: '/metrics'
  metrics.dynatrace.com/port: '8100'
  metrics.dynatrace.com/secure: 'false'
  sidecar.opentelemetry.io/inject: "true"
  # Prometherus Operator annotations (Observability stack: Grafana/Prometheus)
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "8100"
  prometheus.io/scheme: "http"
  
env:
  log_level: "info"
  role: data_plane
  database: "off"
  cluster_mtls: pki
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"
  vitals: "off"
  tracing_instrumentations: "all"
  tracing_sampling_rate: "1.0"
  status_listen: "0.0.0.0:8100 http2"
  port_maps: "80:8000, 443:8443, 8100:8100"
  event_hooks_enabled: "off"
  ssl_cert: "/etc/secrets/kong-proxy-cert/tls.crt"
  ssl_cert_key: "/etc/secrets/kong-proxy-cert/tls.key"
  untrusted_lua_sandbox_requires: resty.jwt
  # plugins: bundled,log-extend

ingressController:
  enabled: false
  installCRDs: false

serviceMonitor:
  # Specifies whether ServiceMonitor for Prometheus operator should be created
  # If you wish to gather metrics from a Kong instance with the proxy disabled (such as a hybrid control plane), see:
  # https://github.com/Kong/charts/blob/main/charts/kong/README.md#prometheus-operator-integration
  enabled: true
  interval: 30s
  # Specifies namespace, where ServiceMonitor should be installed
  namespace: kong-observability
  labels:
    release: kong-prometheus
  targetLabels:
    - release